//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamingSoundtracks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreamingSoundtracks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreamingSoundtracksApp by.
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutButton {
            get {
                return ResourceManager.GetString("AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app uses the following libraries:.
        /// </summary>
        public static string AboutLibs {
            get {
                return ResourceManager.GetString("AboutLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app has no official affiliation to StreamingSoundtracks.com. It uses its public streams and API for audio/image data. For relevant copyright information visit:.
        /// </summary>
        public static string AboutSst {
            get {
                return ResourceManager.GetString("AboutSst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start stream on startup.
        /// </summary>
        public static string AutoplayDescription {
            get {
                return ResourceManager.GetString("AutoplayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} min ago.
        /// </summary>
        public static string HistoryEstimateMinutes {
            get {
                return ResourceManager.GetString("HistoryEstimateMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour ago.
        /// </summary>
        public static string HistoryEstimateOneHour {
            get {
                return ResourceManager.GetString("HistoryEstimateOneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} min ago.
        /// </summary>
        public static string HistoryEstimateOneMinute {
            get {
                return ResourceManager.GetString("HistoryEstimateOneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HistoryTitle {
            get {
                return ResourceManager.GetString("HistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string LengthDescription {
            get {
                return ResourceManager.GetString("LengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played.
        /// </summary>
        public static string PlayedTitle {
            get {
                return ResourceManager.GetString("PlayedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} min.
        /// </summary>
        public static string QueueEstimateMinutes {
            get {
                return ResourceManager.GetString("QueueEstimateMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} hour.
        /// </summary>
        public static string QueueEstimateOneHour {
            get {
                return ResourceManager.GetString("QueueEstimateOneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} min.
        /// </summary>
        public static string QueueEstimateOneMinute {
            get {
                return ResourceManager.GetString("QueueEstimateOneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string QueueTitle {
            get {
                return ResourceManager.GetString("QueueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested by.
        /// </summary>
        public static string RequestedByDescription {
            get {
                return ResourceManager.GetString("RequestedByDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string SettingsBackButton {
            get {
                return ResourceManager.GetString("SettingsBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show queue/history estimates.
        /// </summary>
        public static string ShowQueueHistoryEstimatesDescription {
            get {
                return ResourceManager.GetString("ShowQueueHistoryEstimatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show queue/history title.
        /// </summary>
        public static string ShowQueueHistoryHeaderDescription {
            get {
                return ResourceManager.GetString("ShowQueueHistoryHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View album on StreamingSoundtracks.com.
        /// </summary>
        public static string SstLinkDescription {
            get {
                return ResourceManager.GetString("SstLinkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string VolumeDescription {
            get {
                return ResourceManager.GetString("VolumeDescription", resourceCulture);
            }
        }
    }
}
